### ISSUE TITLE
Target "dist" does not exist

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-js#10]
This is more of minor issue....

Trying to use the ant build script. Normally just plain old "ant" will build the default target, however...

````
ant
Buildfile: build.xml

BUILD FAILED
Target "dist" does not exist in the project "mil-sym-js". 

Total time: 0 seconds
````

**Comment by michael-spinelli** [comment]
That folder is deleted (if it exists) and recreated every time the build is run.  Any chance there's a permissions issue with creating the folder?
