### ISSUE TITLE
Square basic shape symbol does not work

### ISSUE THREAD

**Issue by bevins2** [missioncommand/mil-sym-js#11]
Basic shape SQUARE (symbol code PBS_SQUARE-----) does not work.  Passing in width into the AM field.  Nothing appears on map.

**Comment by mdeutch3** [comment]
A recent change was made to the renderer that sets the rotation to 0 internally if the client does not set the AN azimuth array. Are you running the latest version or setting the azimuth array?

**Comment by bevins2** [comment]
We are not setting AN.  I will pull latest renderer and retest.

**Comment by bevins2** [comment]
Tested latest, still no square.  Here are params we are passing to the renderer:

modifiers:
{"AM":[100],"LINECOLOR":"000000","LINEWIDTH":3}

width: 977
height: 875
symbolCode "PBS_SQUARE-----"
control points: "40,40"

**Comment by michael-spinelli** [comment]
The change Deutch is talking about hasn't made it into an official release yet.

**Comment by mdeutch3** [comment]
If you want to try it with the release you have it should work by adding AN:[0] to the modifiers.

**Comment by bevins2** [comment]
Is there a fix coming for this?

**Comment by bevins2** [comment]
Oh, I just saw Mike's comment.  So try the AN for now, and in future it will be put there.

**Comment by michael-spinelli** [comment]
fixed in release v0.2.0
