### ISSUE TITLE
Circle primitive lacking fill color

### ISSUE THREAD

**Issue by jaybkun** [missioncommand/mil-sym-js#12]
The circle rendered with the correct stroke color but the fillcolor value and line width were ignored.

**Comment by michael-spinelli** [comment]
Which circle?

**Comment by jaybkun** [comment]
GEO_CIRCLE primitive in RenderSymbol2D

**Comment by mdeutch3** [comment]
I don't know what the symbol is. I'm not aware of GEO_CIRCLE. Do you have a 15 character symbol code? Anyway the line color and fill color you show are 00FF00FF which has an alpha value of 0. So you won't see very much.

**Comment by michael-spinelli** [comment]
resolved as an issue in their tester.
