### ISSUE TITLE
Rectangular targets are requiring 2 points

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/mil-sym-js#14]
Created a rectangular target with one point and fed it to the RenderSymbol function and received the following error:

```javascript
{"type":"error","error":"There was an error creating the MilStdSymbol GFFPACSR------X: - symbolID: "GFFPACSR------X" requires a minimum of 2 points. 1 are present. - "}
```
SymbolCode: GFFPACSR------X
position: "-96,35"
bbox: "-152.42640687119285,-12.426406871192853,-67.57359312880715,72.42640687119284"
modifiers: {
  ALTMODE: ""
  AM: [5000,1000]
  AN: [45]
  SYMSTD: 1
  distance:[5000]
}

**Comment by mdeutch3** [comment]
That is the symbol code for FSA Rectangular which does require two points. The symbol code for Rectangular Target is: G*FPATR---****X.
