### ISSUE TITLE
TypeError: Cannot read property 'toHexString' of undefined

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/mil-sym-js#15]
This issue was encountered in WebWorldWind when using the SEC renderer with geojson  format 

sourceClass: "MultiPointHandler"
sourceMethod: "JSONize"

data used:
name: "Discolored Water"
symbolId: "WO-DHHDD----A--"
points: "6.3,24 6.8,24.5 7.3,24"
pixelWidth: 1589
pixelHeight: 966
bound: "-1.3002689902303186,21.76166988385108,7.099433057025056,26.434979493477332"
modifiers: 
CN:"Discolored Water"
GJFORMAT:1
SYMSTD:1

format:2  --> geojson
milstd: 1

fontInfo:
Object
name:"arial"
size:10
style:"bold"

Same problem with PERCHES/STAKES, Drydock, "Underwater Hazard"

**Comment by michael-spinelli** [comment]
I'll check in a fix when my network issues get resolved.

**Comment by michael-spinelli** [comment]
fixed in mil-sym-js release v0.3.24
