### ISSUE TITLE
Hostile battle position symbol has an excessive amount of ENY labels

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/mil-sym-js#20]
The behavior is expected and it is by design. I enhanced the reindeer by adding an option to display ENY labels in all segments, or to only display the label 2 times, one in the north and the other one in the south of the hostile graphics that display ENY.

**Comment by michael-spinelli** [comment]
fix in release 0.3.29
-will open new issue for better placement of the 2 labels
