### ISSUE TITLE
MilStdIconRenderer renders a too-large image for some hostile action points

### ISSUE THREAD

**Issue by eric79** [missioncommand/mil-sym-js#27]
When drawing the following action points with a hostile affiliation, the image that is returned is larger than it intends to be:

* Contact Point
* Decision Point
* Waypoint

For example, here is what is returned from `toDataUrl` for Contact Point:

![image](https://user-images.githubusercontent.com/3160246/37363576-a4b50792-26ce-11e8-8f88-604de0b6f64c.png)

`img.getImageBounds().width` reports that it's 27 pixels wide,
but `img.getImage().width` reports that it's 150 pixels wide (which is true).

As an aside:

1. It appears that the issue only appears for the hostile affiliation
2. `MilStdSVGRenderer` doesn't seem to have the problem.

And by the way ... thanks for making this library available.  It's pretty awesome.

**Comment by michael-spinelli** [comment]
Glad you like it.

What modifiers are you passing into the renderer?
I'm having trouble duplicating the issue

**Comment by eric79** [comment]
Oh, sorry.  Here are the details:

symbolID: `GHGPGPPC----**X`
modifiers: `{SIZE: "40", ICON: false, SYMSTD: 1}`

**Comment by michael-spinelli** [comment]
fixed in release v0.3.31

**Comment by eric79** [comment]
Woohoo!  Thanks!
