### ISSUE TITLE
"TypeError: java.io is undefined" error appears to many times in browser console

### ISSUE THREAD

**Issue by Sufaev** [missioncommand/mil-sym-js#34]
When some erorr occurs inside mil-sym-js, than browser shows hundreds of following errors in log. It looks like some part of code migrated from JAVA to JS tries to create error log file using java.io.* classes.

It is not a critical error, but could you cleanup this case to be able to see real error in mil-sym-js. Because now real error is one of 100 this log errors. 

```
clsUtility WriteFile Severe: TypeError: java.io is undefined - Failed inside WriteFile sm-bc.js:97230:21
LogException sm-bc.js:97230
WriteFile sm-bc.js:94636
PointLatLongToPixels sm-bc.js:120839
LatLongToPixels sm-bc.js:120825
createTGLightFromMilStdSymbol sm-bc.js:117964
renderWithPolylines sm-bc.js:118900 
```

![Знімок екрану з 2019-03-15 17-21-38](https://user-images.githubusercontent.com/12487306/54442220-ecf0d600-4746-11e9-94b4-511e273adee5.png)

**Comment by Sufaev** [comment]
Could you also look at my comments at https://github.com/missioncommand/mil-sym-js/issues/33
The issue was not solved.

**Comment by michael-spinelli** [comment]
Try this and let me know.
There was a java call that didn't get changed.
And I updated the references as you said in issue #33 
[sm-bc.zip](https://github.com/missioncommand/mil-sym-js/files/2972551/sm-bc.zip)

**Comment by Sufaev** [comment]
I can test only on monday. Left my notebook in office.

пт, 15 бер. 2019, 21:10 користувач Michael Spinelli <
notifications@github.com> пише:

**Comment by Sufaev** [comment]
No more "TypeError: java.io is undefined", but GeoPixelConversion3D from issue 33 is still in the same state.
![Знімок екрану з 2019-03-18 09-35-31](https://user-images.githubusercontent.com/12487306/54513970-8abfed00-4961-11e9-8eb7-33e919ed2ace.png)

**Comment by michael-spinelli** [comment]
Sorry, missed GeoPixelConversion3D in the commit somehow.  
We'll carry on in issue #33
