### ISSUE TITLE
NodeJS Package?

### ISSUE THREAD

**Issue by bn-dignitas** [missioncommand/mil-sym-js#35]
I looked for a NodeJS package, but could not find one specific to this project.  Did I overlook it?  If not, are there any plans to publish mil-sym-js as a node package?

**Comment by michael-spinelli** [comment]
There is no NodeJS package.  The project isn't active at the moment so there are no plans to do so.  That may or may not change in a few weeks.

**Comment by bn-dignitas** [comment]
Thanks for the quick answer.
