### ISSUE TITLE
GeoJSON format places text modifiers in unsuspecting positions

### ISSUE THREAD

**Issue by hobiedude** [missioncommand/mil-sym-js#4]
If I render a tactical graphic using the KML format the text modifiers appear as one would expect within in the multipoint graphic.

Attachment 1:
![screenhunter_01 nov 21 12 57](https://cloud.githubusercontent.com/assets/3707428/5148706/c4d2c4e6-717e-11e4-90f2-1a77757bed39.gif)

If I render the same tactical graphic using the GeoJSON format the GeoJSON (Points, Markers) appear outside the graphic.

Attachment 2:
![screenhunter_04 nov 21 13 07](https://cloud.githubusercontent.com/assets/3707428/5148763/62b8a072-717f-11e4-9356-5816c1443137.gif)

The polygon is a little hard to see but it appears in the lower third of the image,

Feel free to contact me for additional information.

J. Stoy

**Comment by michael-spinelli** [comment]
No reply from hobiedude, the fix works for us, closing...

**Comment by brianwheeler** [comment]
Hi, just wondering if this is related. Here is In image from my program, and the same symbol with the same points in your demo program. Is the text supposed to be in those positions? I would expect it to be lined up with the ends of the lines, but the rightmost label is far to the left.
There is no text positioning information and text alignment is 'lm'.
Thanks
![textalignment2](https://cloud.githubusercontent.com/assets/10157798/5803872/92a3aa10-9fcf-11e4-9454-466637ecaac7.png)
![textalignment1](https://cloud.githubusercontent.com/assets/10157798/5803876/98753b66-9fcf-11e4-8be8-c69dd6e26ed9.png)

**Comment by michael-spinelli** [comment]
This is unrelated to the bug above.

The text has font information, a geo coordinate location and 'lm' for left middle alignment as well as a rotation angle.  Was there some other text positioning information you needed?

Label placement is off so we're looking into that.

**Comment by brianwheeler** [comment]
Thanks for the reply.

Yes, it is just the label placement being off that I was referring to.

For the text positioning, I just meant that I hadn't added anything that would cause the positions to be off and everything (offsets, etc) came from the renderer as '0' or absent (I wasn't missing anything that would align the text when I rendered it on the map in my example).
