### ISSUE TITLE
Can't render correct symbol "Wind Plot"

### ISSUE THREAD

**Issue by ivanKyka** [missioncommand/mil-sym-js#41]
![image](https://user-images.githubusercontent.com/35963186/140323685-6929f0db-44c1-49ba-be35-158942a24e4d.png)

As I see in config, symbol requires 2 points for drawing, but drawed only with one point.
Also symbol doesn't changes when I change modifiers Z and Q

Can you help me detect the problem?

**Comment by michael-spinelli** [comment]
Wind Plot was never properly implemented.
