### ISSUE TITLE
Error when use SinglePointSVGRenderer.renderSPTG

### ISSUE THREAD

**Issue by ivanKyka** [missioncommand/mil-sym-js#44]
When i use method renderSPTG I have an error ` TypeError: ti.getTextBounds is not a function`

Call params:
symbolId: 'GUFPPCR-------X'
modifiers: {
KEEPUNITRATIO: true
SIZE: 60
T: "123123"
}

I found the problem. In file `SinglePointSVGRenderer.js:2793` Renderer trying to call method `getTextBounds` which not exist. 
`var labelWidth = ti.getTextBounds().getWidth();`

**Comment by michael-spinelli** [comment]
Yes, that is a problem.  I'll take a look.  Probably a small fix.

**Comment by michael-spinelli** [comment]
Made 2 updates to the code:
-SVGTextInfo, added missing getTextBounds function
-SinglePointSVGRenderer, adjusted scaling of Single Point Tactical Graphics when KeepUnitRatio == true.  It should be closer to the scaling in SinglePointRenderer.

Let me know if that works for you.

**Comment by ivanKyka** [comment]
Works great thanks!
