### ISSUE TITLE
Problem with changing default friend color when use bundled files from samples

### ISSUE THREAD

**Issue by ivanKyka** [missioncommand/mil-sym-js#49]
Hi @michael-spinelli !
Now I'm working on migrating our application to Web Workers.
For that purpose, I use two files from samples: `m-c.js` and `sv-c.js`, which were imported into my custom worker. 
Rendering works great but I have an error when changing the default friend color to blue.
As I see, problem into file `armyc2.c2sd.renderer.utilities.RendererSettings`. Original files have all the necessary methods, but they are missing in bundled files.

Code which I use to change graphic color:
```
const friendlyUnitColor = new Color(0, 192, 255);

RendererSettings.setFriendlyGraphicFillColor(friendlyUnitColor);
RendererSettings.setFriendlyGraphicLineColor(friendlyUnitColor);
RendererSettings.setFriendlyUnitFillColor(friendlyUnitColor);
RendererSettings.setFriendlyUnitLineColor(friendlyUnitColor);

SymbolUtilities.rendererSettings.setFriendlyGraphicFillColor(friendlyUnitColor);
SymbolUtilities.rendererSettings.setFriendlyGraphicLineColor(friendlyUnitColor);

SymbolUtilities.rendererSettings.setFriendlyUnitFillColor(friendlyUnitColor);
SymbolUtilities.rendererSettings.setFriendlyUnitLineColor(friendlyUnitColor);
```

**Comment by michael-spinelli** [comment]
I'll take a look.

**Comment by michael-spinelli** [comment]
Looks like those files in the samples folder haven't been updated in a while.  If you take the files from the last release and copy them into the samples folder, that should fix your problems.  We should've had the build script do that automatically but we didn't.  Let me know if that fixes your problem.

**Comment by ivanKyka** [comment]
All works great! 
Thanks for your help!
