### ISSUE TITLE
Multipoint objects with different lines do not give any geometries

### ISSUE THREAD

**Issue by brianwheeler** [missioncommand/mil-sym-js#5]
I am trying to render multipoint 2525C graphics in GeoJSON format. I can successfully render most of the graphics, but I can't manage obstacles, ditches, basically anything with a zig-zag, crenellated, or otherwise odd lines (example: Wire Obstacle Double Fence). They just don't give me any geometries at all.
Is there a modifier I need to provide? Maybe they need a scale value or something?

**Comment by michael-spinelli** [comment]
I'll take a look

**Comment by michael-spinelli** [comment]
Working for me on a 2D openLayers map.  I tried Wire Obstacle Double Fence.

You can take a look at the sample code from this post (get the sample from the 3rd post):
https://groups.google.com/forum/#!topic/mission-command-milstd-renderer/LMENUbBKeEI

Just change the symbol ID in function buildSymbol2D.

What map are you using to try this out? 
Can I see the inputs you're providing to the renderer?
![double fence wire obstacle](https://cloud.githubusercontent.com/assets/5972575/5748653/b32f11ca-9c0f-11e4-8cd1-b4595a168af6.png)

**Comment by brianwheeler** [comment]
I have it rendering now. The problem is I am passing in a very small portion of my map as a bounding box for each graphic, so the graphic is being scaled down very small.

For most graphics this works fine, but for these graphics it fails to return a geometry. I think maybe there are too many points in the geometry (in the example graphic, there will be a lot of the little X symbols) so it fails?

For my purposes, I just have to readjust the scale and rerender for every zoom level like your example does (I need to do that anyway, I just haven't implemented it yet) and it will work fine.

Thanks for your help!

**Comment by michael-spinelli** [comment]
no problem
