### ISSUE TITLE
Incorrect graphic rendering related to bbox

### ISSUE THREAD

**Issue by ivanKyka** [missioncommand/mil-sym-js#52]
Hi, @michael-spinelli !
I'm still working on migrating my application to web workers.
When I check graphics, I found a few cases of incorrect rendering.
I didn't find the source of the problem, but I think that is related to bbox which I pass into params

Expected result 
![image](https://user-images.githubusercontent.com/35963186/193222919-4c90d53c-60ec-49dd-9672-31b98e4baadf.png)

The current result which I have:
![image](https://user-images.githubusercontent.com/35963186/193223166-2e2f0b91-0e05-4a5f-8dbc-dfb3f0b24702.png)

Params which I pass into `sec.web.renderer.SECWebRenderer.RenderSymbol2D`:
```
    "id": "ID",
    "name": "",
    "description": "DESCR",
    "sidc": "GAGPOLAGM-----X",
    "points": "26.016182667994155,48.93776674802398 24.999947316431705,48.36439019575385 23.599190480494276,48.48468488803118 24.625140277622883,49.007371341140534",
    "pixelHeight": 1000,
    "pixelWidth": 1000,
    "bbox": "-32.6013710429282,26.756551592436782,91.06073833203895,64.44017897705172",
    "modifiers": {},
    "format": 2,
    "symstd": 1
```

**Comment by ivanKyka** [comment]
I think that problem is caused by PointConversion util. That utility is created from pixelHeight, pixelWidth and bbox.
Maybe I pass the wrong params into the method call?

**Comment by ivanKyka** [comment]
Found it! 
PixelWidth and PixelHeight must be proportional to bbox width and height

**Comment by michael-spinelli** [comment]
Glad you found it!  Sorry I didn't get a chance to look into it.

**Comment by ivanKyka** [comment]
Maybe should write comments into samples? It will help for next users
